name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package
      run: dotnet pack --no-build --output ./

    - name: Upload package
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v2.2.2
      with:
        name: package
        path: ./*.nupkg
        retention-days: 7

  deploy:
    if: ${{ github.event_name == 'push' }}

    environment:
      name: Main
    
    runs-on: ubuntu-latest
    
    needs: [build]
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: package
    - name: Publish NuGet
      run: dotnet nuget push ./*.nupkg --api-key '${{secrets.NUGET_API_KEY}}' --source https://api.nuget.org/v3/index.json


